version: 2
jobs:
  build:
    working_directory: ~/tmp
    docker:
      - image: circleci/node:10
    steps:
      - checkout
      - run: npm install
      - run: npm test
      - run: sudo apt-get update && sudo apt-get install -y python-dev
      - run: sudo curl -O https://bootstrap.pypa.io/get-pip.py
      - run: sudo python get-pip.py
      - run: sudo pip install awscli --upgrade
      - run: aws --version
      - run: aws s3 ls
      - run: npm run deploy
